### ISSUE TITLE
how to use it without node.js

### ISSUE THREAD

**Issue by goltus** [thlorenz/d3-gauge#2]
Hi, 

I would love to use this plugin but it seems the only way to do it is via node.js. Is it possible to implement it without node.js, as a standalone js plugin for d3.js? 

Thanks,
Nikhil

**Comment by simonpa71** [comment]
Hello,
I got this to work in a browser (hack hack) by commenting out the first section of d3-gauge.js (exports and other nodejs stuff before the instructions), and including d3-gauge.js, d3.js, mutable.js and the simple.css and simple.js in the top level document.
In simple.js I replaced the module.exports with a var: 
    // var go = module.exports = {
    var defaultOpts = {
This works ok. Thanks [thlorenz](https://github.com/thlorenz) for sharing with the community!

**Comment by coli** [comment]
+1
